import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const meshedDisplay = localFont({
  src: "./fonts/MeshedDisplay-Black.woff",
  variable: "--font-meshed-display",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chef Tee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${meshedDisplay.variable} relative antialiased`}
      >
        <div className="fixed z-[9999]  top-11 w-9/12 left-1/2 -translate-x-1/2 ">
            <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
